<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class Animal extends Model
{
    protected $fillable = [
        'recinto_id',
        'actividad_id',
    ];

    public function cuidadoranimal()
    {
        return $this->belongsTo('App\Models\CuidadorAnimal');
    }

    public function recintoanimal()
    {
        return $this->belongsTo('App\Models\RecintoAnimal');
    }

    public function actividad()
    {
        return $this->belongsTo('App\Models\Actividad');
    }

    public function especieanimal()
    {
        return $this->belongsTo('App\Models\EspecieAnimal');
    }
}
